[DOCS] add comment to ALLOWED_METHODS section about enabling HTTP POST
bunkerity/bunkerweb pull request #1375
Opened 2024-07-23 14:21 UTC by spwoodcock

## Issue

- The `ALLOWED_METHODS` variable is a bit hidden in the settings, under `Miscellaneous` https://docs.bunkerweb.io/latest/settings/#miscellaneous
- The default of `GET|POST|HEAD` is understandably very strict, as many users may run bunkerweb in front of simple applications that only serve content.
- Application developers using bunkerweb in front of their apps will most likely need `POST` (amonst others like `PATCH`, `DELETE`, etc).
- A HTTP `POST` require actually requires two requests from browsers:
  - A CORS pre-flight request using `OPTIONS` first.
  - Then the `POST` request if CORS doesn't fail.

## Solution

- Added a small note in the docs `ALLOWED_METHODS`, located: https://docs.bunkerweb.io/latest/security-tuning/#allowed-methods:

```
Note that if `POST` is required, then `OPTIONS` should also be specified to allow for the CORS pre-flight request.
```

## Notes

- It's probably possible to enable `OPTIONS` by default if `POST` is included, but this is probably a bad idea.
- Options should be defined explicitly rather than implicitly.

2024-07-24 11:46 UTC, TheophileDiot commented
Hi, thank you for opening this P/R. Indeed this detail is missing in the documentation and can be confusing.

2024-07-24 11:48 UTC, TheophileDiot commented on docs/security-tuning.md
Using the MkDocs admonitions feature could enhance the visibility of the warning. You can find more details here: [MkDocs Admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types).

2024-07-24 11:49 UTC, TheophileDiot requested changes
Waiting for the recommended changes to be implemented.

2024-09-17 10:11 UTC, merged

2024-09-17 10:11 UTC, fl0ppy-d1sk commented
Thanks @spwoodcock !