Add setting to intercept specifics error codes
bunkerity/bunkerweb pull request #383
Opened 2022-12-07 14:04 UTC by quentin-fougereau

This pull request is related to the issue [#379](https://github.com/bunkerity/bunkerweb/issues/379).

I propose a new setting INTERCEPTED_ERROR_CODES to choose which error codes will be intercepted by bunkerweb.

The value accepted by this setting is a list of error codes separated with whitespace.

The default value is INTERCEPTED_ERROR_CODES=400 401 403 404 405 413 429 500 501 502 503 504.

2022-12-07 14:12 UTC, TheophileDiot commented
Thank you for this P/R, we really appreciate your contribution, we'll review it asap !

2023-01-11 08:28 UTC, TheophileDiot requested changes
We need more information about the changes in the [.github/workflows/dev.yml](https://github.com/bunkerity/bunkerweb/pull/383/files#diff-914da273e1d936250929f1160bdd8be46aa865099502b04b471fe734f6b644dd) file

2023-01-11 14:01 UTC, quentin-fougereau commented
It's not a change from me. It is from commit 613d757d3f24825c4ae0d7824c5ac57814b6a3c0.
Maybe I did wrong, I'm not used to make pull requests.

2023-01-11 15:23 UTC, TheophileDiot commented
@quentin-fougereau If you don't want this change to persist you can revert your commit or create another branch that doesn't have the following lines

2023-01-11 16:10 UTC, TheophileDiot approved these changes

2023-01-20 10:12 UTC, merged