Staging
bunkerity/bunkerweb pull request #431
Opened 2023-04-03 08:19 UTC by gin-gitaxias

Adding reverse-scan core plugin

2023-04-03 08:49 UTC, TheophileDiot commented on src/common/core/reverse-scan/plugin.json
- Maybe be more precise in the `help` sections.
 - Change the `labels` to a more user friendly text, especially for the `TIMEOUT`
 - Change the names of the settings `TIMEOUT` and `PORT_SCAN` so that users know what does it change (maybe `REVERSE_SCAN_TIMEOUT` and `REVERSE_SCAN_PORT_SCAN`)
 - Rename the `REVERSE_SCAN` setting to follow the other settings with the `USE_` prefix

2023-04-03 09:59 UTC, TheophileDiot requested changes
Follow the comments.

2023-04-03 12:10 UTC, gin-gitaxias commented on src/common/core/reverse-scan/plugin.json
done, i've also modified _M:scan()

2023-04-04 15:16 UTC, fl0ppy-d1sk approved these changes

2023-04-04 15:16 UTC, fl0ppy-d1sk approved these changes

2023-04-04 15:16 UTC, fl0ppy-d1sk approved these changes

2023-04-05 08:58 UTC, TheophileDiot approved these changes

2023-04-05 08:58 UTC, merged